splits: 
  genAbsPhiS: [0.0,0.05,0.1,0.2,0.3,0.4,0.5,0.7,1.0,1.5,2.5,4.0,100.0]
  recoAbsPhiS: [0.0,0.05,0.1,0.2,0.3,0.4,0.5,0.7,1.0,1.5,2.5,4.0,100.0]
  sigmaMoM_decorr: [0.0, 0.0106, 0.0146, 0.0396]
  # absdZ: [0.0,1.0,100.]
 
variables: 
  CMS_hgg_mass: [100, 180]
  weight: [-inf, inf]
  centralObjectWeight: [-1000, 1000]
  dZ: [-inf, inf]
  processIndex: [0,100]

cut: 'leadmva>0.397 and subleadmva>0.397'

weight: 'weight'

systVars: []

procs:
  IA_125: 'InsideAcceptance_125_13TeV'
  OA_125: 'OutsideAcceptance_125_13TeV'
  IA_120: 'InsideAcceptance_120_13TeV'
  OA_120: 'OutsideAcceptance_120_13TeV'
  IA_130: 'InsideAcceptance_130_13TeV'
  OA_130: 'OutsideAcceptance_130_13TeV'
  Data: 'Data_13TeV'
  
categories: ['SigmaMpTTag_0']

filenames:
  IA_125: 'reducedAbsPhiSIA_genAbsPhiS_nominal.root'
  OA_125: 'reducedAbsPhiSOA__nominal.root'
  IA_120: 'reducedAbsPhiSIA_genAbsPhiS_nominal.root'
  OA_120: 'reducedAbsPhiSOA__nominal.root'
  IA_130: 'reducedAbsPhiSIA_genAbsPhiS_nominal.root'
  OA_130: 'reducedAbsPhiSOA__nominal.root'
  Data: 'reducedAbsPhiSData__nominal.root'
  
treepath: 'tagsDumper/trees'

formulas: 
  recoAbsPhiS: 'abs(@diffHTan(recoLeadPhi, recoSubleadPhi) * @diffHSech(recoLeadEta, recoSubleadEta))'
  genAbsPhiS: 'abs(@diffHTan(genLeadPhi, genSubleadPhi) * @diffHSech(genLeadEta, genSubleadEta))'

functions:
  deltaPhi: "def deltaPhi(phi1, phi2):\n\t ret = phi1 - phi2\n\t ret[ret >= np.pi] = ret[ret >= np.pi] - 2*np.pi\n\t ret[ret < -np.pi] = ret[ret < -np.pi] + 2*np.pi\n\t return ret"
  diffHTan: "def diffHTan(phi1, phi2):\n\t return np.tan((np.pi - deltaPhi(phi1, phi2))/2.)"
  diffHSech: "def diffHSech(eta1, eta2):\n\t return 1./(np.cosh((eta1 - eta2)/2.))"
