splits: 
  genAbsZeppenfeldEtaJets4p7: [0.0,0.2,0.5,0.85,1.2,1.7,10.0]
  recoAbsZeppenfeldEtaJets4p7: [0.0,0.2,0.5,0.85,1.2,1.7,10.0]
  sigmaMoM_decorr: [0.0, 0.0106, 0.0146, 0.0396]
  # absdZ: [0.0,1.0,100.]
 
variables: 
  CMS_hgg_mass: [100, 180]
  weight: [-inf, inf]
  centralObjectWeight: [-1000, 1000]
  dZ: [-inf, inf]
  processIndex: [0,100]

cut: 'leadmva>0.397 and subleadmva>0.397'

phasespace:
  gen: 'genJet4p7Eta0>-999 and genJet4p7Eta1>-999 and genJet4p7Pt0>30 and genJet4p7Pt1>30 and abs(genJet4p7Eta0)<4.7 and abs(genJet4p7Eta1)<4.7'
  reco: 'recoJet4p7Eta0>-999 and recoJet4p7Eta1>-999 and recoJet4p7Pt0>30 and recoJet4p7Pt1>30 and abs(recoJet4p7Eta0)<4.7 and abs(recoJet4p7Eta1)<4.7'

weight: 'weight'

systVars: []

procs:
  IA_125: 'InsideAcceptance_125_13TeV'
  OA_125: 'OutsideAcceptance_125_13TeV'
  IA_120: 'InsideAcceptance_120_13TeV'
  OA_120: 'OutsideAcceptance_120_13TeV'
  IA_130: 'InsideAcceptance_130_13TeV'
  OA_130: 'OutsideAcceptance_130_13TeV'
  Data: 'Data_13TeV'
  
categories: ['SigmaMpTTag_0']

filenames:
  IA_125: 'reducedAbsZeppenfeldEtaJets4p7IA_genAbsZeppenfeldEtaJets4p7_nominal.root'
  OA_125: 'reducedAbsZeppenfeldEtaJets4p7OA__nominal.root'
  IA_120: 'reducedAbsZeppenfeldEtaJets4p7IA_genAbsZeppenfeldEtaJets4p7_nominal.root'
  OA_120: 'reducedAbsZeppenfeldEtaJets4p7OA__nominal.root'
  IA_130: 'reducedAbsZeppenfeldEtaJets4p7IA_genAbsZeppenfeldEtaJets4p7_nominal.root'
  OA_130: 'reducedAbsZeppenfeldEtaJets4p7OA__nominal.root'
  Data: 'reducedAbsZeppenfeldEtaJets4p7Data__nominal.root'
  
treepath: 'tagsDumper/trees'

formulas: 
  recoAbsZeppenfeldEtaJets4p7: 'abs(0.5*(recoJet4p7Eta0 + recoJet4p7Eta1) - recoEta)'
  genAbsZeppenfeldEtaJets4p7: 'abs(0.5*(genJet4p7Eta0 + genJet4p7Eta1) - genEta)'
