splits: 
  genNjets2p5: [-0.5,0.5,1.5,2.5,3.5,100]
  recoNjets2p5: [-0.5,0.5,1.5,2.5,3.5,100]
  sigmaMoM_decorr: [0.0, 0.01076, 0.0165, 0.0332]
  # absdZ: [0.0,1.0,100.]
 
variables: 
  CMS_hgg_mass: [100, 180]
  weight: [-inf, inf]
  centralObjectWeight: [-1000, 1000]
  dZ: [-inf, inf]
  processIndex: [0,100]

cut: 'leadmva>0.46 and subleadmva>0.46'

weight: 'weight'

systVars: ['LooseMvaSF','PreselSF','electronVetoSF','TriggerWeight','FracRVWeight','ElectronIDWeight','ElectronRecoWeight','JetBTagCutWeight','JetBTagReshapeWeight']

# 'MuonIDWeight' e.metaConditions["MUON_ID"]),direction))
# 'MuonIsoWeight'            ize.metaConditions['MUON_ISO']),direction))
procs:
  IA_125: 'InsideAcceptance_125_13TeV'
  OA_125: 'OutsideAcceptance_125_13TeV'
  IA_120: 'InsideAcceptance_120_13TeV'
  OA_120: 'OutsideAcceptance_120_13TeV'
  IA_130: 'InsideAcceptance_130_13TeV'
  OA_130: 'OutsideAcceptance_130_13TeV'
  Data: 'Data_13TeV'
  
categories: ['SigmaMpTTag_0', 'SigmaMpTTag_0_MvaShiftUp01sigma', 'SigmaMpTTag_0_MvaShiftDown01sigma']

filenames:
  IA_125: 'reducedNjets2p5IA_genNjets2p5_nominal.root'
  OA_125: 'reducedNjets2p5OA__nominal.root'
  IA_120: 'reducedNjets2p5IA_genNjets2p5_nominal.root'
  OA_120: 'reducedNjets2p5OA__nominal.root'
  IA_130: 'reducedNjets2p5IA_genNjets2p5_nominal.root'
  OA_130: 'reducedNjets2p5OA__nominal.root'
  Data: 'reducedNjets2p5Data__nominal.root'
  
treepath: 'tagsDumper/trees'

# formulas: 
#  absdZ: 'abs(dZ)'
