splits: 
  genTauCJets4p7: [-1000.0,15.0,20.0,30.0,50.0,80.0,10000.0]
  recoTauCJets4p7: [-1000.0,15.0,20.0,30.0,50.0,80.0,10000.0]
  sigmaMoM_decorr: [0.0, 0.01076, 0.0165, 0.0332]
   
variables: 
  CMS_hgg_mass: [100, 180]
  weight: [-inf, inf]

nominalVariables:
  centralObjectWeight: [-1000, 1000]
  dZ: [-inf, inf]
  processIndex: [0,100]

cut: 'leadmva>0.46 and subleadmva>0.46'

phasespace:
  gen: 'genTauCJets4p7>15 and genJet4p7Energy0>-999 and genJet4p7Pt0>30 and abs(genJet4p7Eta0)<4.7'
  reco: 'recoTauCJets4p7>15 and recoJet4p7Energy0>-999 and recoJet4p7Pt0>30 and abs(recoJet4p7Eta0)<4.7'

weight: 'weight'

systVars: ['PreselSF','electronVetoSF','TriggerWeight','FracRVWeight']

theoryWeights :
  pdfWeights: 60
  alphaSWeights: 2
  scaleWeights: 9

procs:
  IA_125: 'InsideAcceptance_125_13TeV'
  OA_125: 'OutsideAcceptance_125_13TeV'
  IA_120: 'InsideAcceptance_120_13TeV'
  OA_120: 'OutsideAcceptance_120_13TeV'
  IA_130: 'InsideAcceptance_130_13TeV'
  OA_130: 'OutsideAcceptance_130_13TeV'
  Data: 'Data_13TeV'
  
categories: ['SigmaMpTTag_0', 'SigmaMpTTag_0_FNUFEBDown01sigma', 'SigmaMpTTag_0_FNUFEBUp01sigma', 'SigmaMpTTag_0_FNUFEEDown01sigma', 'SigmaMpTTag_0_FNUFEEUp01sigma', 'SigmaMpTTag_0_JECAbsolute2018Down01sigma', 'SigmaMpTTag_0_JECAbsolute2018Up01sigma', 'SigmaMpTTag_0_JECAbsoluteDown01sigma', 'SigmaMpTTag_0_JECAbsoluteUp01sigma', 'SigmaMpTTag_0_JECBBEC12018Down01sigma', 'SigmaMpTTag_0_JECBBEC12018Up01sigma', 'SigmaMpTTag_0_JECBBEC1Down01sigma', 'SigmaMpTTag_0_JECBBEC1Up01sigma', 'SigmaMpTTag_0_JECDown01sigma', 'SigmaMpTTag_0_JECEC22018Down01sigma', 'SigmaMpTTag_0_JECEC22018Up01sigma', 'SigmaMpTTag_0_JECEC2Up01sigma', 'SigmaMpTTag_0_JECEC2Down01sigma', 'SigmaMpTTag_0_JECFlavorQCDDown01sigma', 'SigmaMpTTag_0_JECFlavorQCDUp01sigma', 'SigmaMpTTag_0_JECHF2018Down01sigma', 'SigmaMpTTag_0_JECHFDown01sigma', 'SigmaMpTTag_0_JECHF2018Up01sigma', 'SigmaMpTTag_0_JECHFUp01sigma', 'SigmaMpTTag_0_JECRelativeBalDown01sigma', 'SigmaMpTTag_0_JECRelativeSample2018Down01sigma', 'SigmaMpTTag_0_JECRelativeBalUp01sigma', 'SigmaMpTTag_0_JECRelativeSample2018Up01sigma', 'SigmaMpTTag_0_JECUp01sigma', 'SigmaMpTTag_0_JERDown01sigma', 'SigmaMpTTag_0_JERUp01sigma', 'SigmaMpTTag_0_JetHEMDown01sigma', 'SigmaMpTTag_0_JetHEMUp01sigma', 'SigmaMpTTag_0_MCScaleGain1EBDown01sigma', 'SigmaMpTTag_0_MCScaleGain1EBUp01sigma', 'SigmaMpTTag_0_MCScaleGain6EBDown01sigma', 'SigmaMpTTag_0_MCScaleGain6EBUp01sigma', 'SigmaMpTTag_0_MCScaleHighR9EBDown01sigma', 'SigmaMpTTag_0_MCScaleHighR9EBUp01sigma', 'SigmaMpTTag_0_MCScaleHighR9EEDown01sigma', 'SigmaMpTTag_0_MCScaleHighR9EEUp01sigma', 'SigmaMpTTag_0_MCScaleLowR9EBDown01sigma', 'SigmaMpTTag_0_MCScaleLowR9EBUp01sigma', 'SigmaMpTTag_0_MCScaleLowR9EEDown01sigma', 'SigmaMpTTag_0_MCScaleLowR9EEUp01sigma', 'SigmaMpTTag_0_MCSmearHighR9EBPhiDown01sigma', 'SigmaMpTTag_0_MCSmearHighR9EBPhiUp01sigma', 'SigmaMpTTag_0_MCSmearHighR9EBRhoDown01sigma', 'SigmaMpTTag_0_MCSmearHighR9EBRhoUp01sigma', 'SigmaMpTTag_0_MCSmearHighR9EEPhiDown01sigma', 'SigmaMpTTag_0_MCSmearHighR9EEPhiUp01sigma', 'SigmaMpTTag_0_MCSmearHighR9EERhoDown01sigma', 'SigmaMpTTag_0_MCSmearHighR9EERhoUp01sigma', 'SigmaMpTTag_0_MCSmearLowR9EBPhiDown01sigma', 'SigmaMpTTag_0_MCSmearLowR9EBPhiUp01sigma', 'SigmaMpTTag_0_MCSmearLowR9EBRhoDown01sigma', 'SigmaMpTTag_0_MCSmearLowR9EBRhoUp01sigma', 'SigmaMpTTag_0_MCSmearLowR9EEPhiDown01sigma', 'SigmaMpTTag_0_MCSmearLowR9EEPhiUp01sigma', 'SigmaMpTTag_0_MCSmearLowR9EERhoDown01sigma', 'SigmaMpTTag_0_MCSmearLowR9EERhoUp01sigma', 'SigmaMpTTag_0_MaterialCentralBarrelDown01sigma', 'SigmaMpTTag_0_MaterialCentralBarrelUp01sigma', 'SigmaMpTTag_0_MaterialForwardDown01sigma', 'SigmaMpTTag_0_MaterialForwardUp01sigma', 'SigmaMpTTag_0_MaterialOuterBarrelDown01sigma', 'SigmaMpTTag_0_MaterialOuterBarrelUp01sigma', 'SigmaMpTTag_0_MvaShiftDown01sigma', 'SigmaMpTTag_0_MvaShiftUp01sigma', 'SigmaMpTTag_0_PUJIDShiftDown01sigma', 'SigmaMpTTag_0_PUJIDShiftUp01sigma', 'SigmaMpTTag_0_ShowerShapeHighR9EBDown01sigma', 'SigmaMpTTag_0_ShowerShapeHighR9EBUp01sigma', 'SigmaMpTTag_0_ShowerShapeHighR9EEDown01sigma', 'SigmaMpTTag_0_ShowerShapeHighR9EEUp01sigma', 'SigmaMpTTag_0_ShowerShapeLowR9EBDown01sigma', 'SigmaMpTTag_0_ShowerShapeLowR9EBUp01sigma', 'SigmaMpTTag_0_ShowerShapeLowR9EEDown01sigma', 'SigmaMpTTag_0_ShowerShapeLowR9EEUp01sigma', 'SigmaMpTTag_0_SigmaEOverEShiftDown01sigma', 'SigmaMpTTag_0_SigmaEOverEShiftUp01sigma', 'SigmaMpTTag_0_metJecUncertaintyDown01sigma', 'SigmaMpTTag_0_metJecUncertaintyUp01sigma', 'SigmaMpTTag_0_metJerUncertaintyDown01sigma', 'SigmaMpTTag_0_metJerUncertaintyUp01sigma', 'SigmaMpTTag_0_metPhoUncertaintyDown01sigma', 'SigmaMpTTag_0_metPhoUncertaintyUp01sigma', 'SigmaMpTTag_0_metUncUncertaintyDown01sigma', 'SigmaMpTTag_0_metUncUncertaintyUp01sigma']

correlatedSyst: ['JEC', 'ScaleHighR9EB', 'ScaleHighR9EE', 'ScaleLowR9EB', 'ScaleLowR9EE', 'ScaleGain6EB', 'ScaleGain1EB', 'SmearHighR9EBPhi','SmearHighR9EBRho','SmearHighR9EEPhi','SmearHighR9EERho','SmearLowR9EBPhi','SmearLowR9EBRho','SmearLowR9EEPhi','SmearLowR9EERho', 'Material', 'NonLinearity', 'Geant4', 'LightYield', 'Absolute']

filenames:
  IA_125: 'reducedTauCJets4p7IA_genTauCJets4p7_nominal.root'
  OA_125: 'reducedTauCJets4p7OA__nominal.root'
  IA_120: 'reducedTauCJets4p7IA_genTauCJets4p7_nominal.root'
  OA_120: 'reducedTauCJets4p7OA__nominal.root'
  IA_130: 'reducedTauCJets4p7IA_genTauCJets4p7_nominal.root'
  OA_130: 'reducedTauCJets4p7OA__nominal.root'
  Data: 'reducedTauCJets4p7Data__nominal.root'
  
treepath: 'tagsDumper/trees'

formulas: 
  recoTauCJet4p70: 'sqrt(recoJet4p7Energy0**2-recoJet4p7Pz0**2)/(2*cosh(recoJet4p7Rapidity0-recoRapidity))'
  genTauCJet4p70: 'sqrt(genJet4p7Energy0**2-genJet4p7Pz0**2)/(2*cosh(genJet4p7Rapidity0-genRapidity))'
  recoTauCJet4p71: 'sqrt(recoJet4p7Energy1**2-recoJet4p7Pz1**2)/(2*cosh(recoJet4p7Rapidity1-recoRapidity))'
  genTauCJet4p71: 'sqrt(genJet4p7Energy1**2-genJet4p7Pz1**2)/(2*cosh(genJet4p7Rapidity1-genRapidity))'
  recoTauCJet4p72: 'sqrt(recoJet4p7Energy2**2-recoJet4p7Pz2**2)/(2*cosh(recoJet4p7Rapidity2-recoRapidity))'
  genTauCJet4p72: 'sqrt(genJet4p7Energy2**2-genJet4p7Pz2**2)/(2*cosh(genJet4p7Rapidity2-genRapidity))'
  recoTauCJet4p73: 'sqrt(recoJet4p7Energy3**2-recoJet4p7Pz3**2)/(2*cosh(recoJet4p7Rapidity3-recoRapidity))'
  genTauCJet4p73: 'sqrt(genJet4p7Energy3**2-genJet4p7Pz3**2)/(2*cosh(genJet4p7Rapidity3-genRapidity))'
  recoTauCJet4p74: 'sqrt(recoJet4p7Energy4**2-recoJet4p7Pz4**2)/(2*cosh(recoJet4p7Rapidity4-recoRapidity))'
  genTauCJet4p74: 'sqrt(genJet4p7Energy4**2-genJet4p7Pz4**2)/(2*cosh(genJet4p7Rapidity4-genRapidity))'
  recoTauCJet4p75: 'sqrt(recoJet4p7Energy5**2-recoJet4p7Pz5**2)/(2*cosh(recoJet4p7Rapidity5-recoRapidity))'
  genTauCJet4p75: 'sqrt(genJet4p7Energy5**2-genJet4p7Pz5**2)/(2*cosh(genJet4p7Rapidity5-genRapidity))'
  recoTauCJets4p7: '@myMax(recoTauCJet4p70,recoTauCJet4p71,recoTauCJet4p72,recoTauCJet4p73,recoTauCJet4p74,recoTauCJet4p75)'
  genTauCJets4p7: '@myMax(genTauCJet4p70,genTauCJet4p71,genTauCJet4p72,genTauCJet4p73,genTauCJet4p74,genTauCJet4p75)'

functions:
  myMax: "def myMax(val0, val1, val2, val3, val4, val5):\n\t ret = np.amax(np.array([val0, val1, val2, val3, val4, val5]), axis=0)\n\t return ret"

