splits: 
  genAbsDeltaPhiGgJet2p50: [0.0,2.0,2.6,2.85,3.0,3.07,3.2]
  recoAbsDeltaPhiGgJet2p50: [0.0,2.0,2.6,2.85,3.0,3.07,3.2]
  sigmaMoM_decorr: [0.0, 0.0116, 0.0161, 0.0306]
  # absdZ: [0.0,1.0,100.]
 
variables: 
  CMS_hgg_mass: [100, 180]
  weight: [-inf, inf]
  centralObjectWeight: [-1000, 1000]
  NNLOPSweight: [-inf, inf]
  dZ: [-inf, inf]
  processIndex: [0,100]

cut: 'leadmva>0.46 and subleadmva>0.46'

weight: 'weight*NNLOPSweight'

systVars: []

procs:
  IA_125: 'InsideAcceptance_125_13TeV'
  OA_125: 'OutsideAcceptance_125_13TeV'
  IA_120: 'InsideAcceptance_120_13TeV'
  OA_120: 'OutsideAcceptance_120_13TeV'
  IA_130: 'InsideAcceptance_130_13TeV'
  OA_130: 'OutsideAcceptance_130_13TeV'
  Data: 'Data_13TeV'
  
categories: ['SigmaMpTTag_0']

filenames:
  IA_125: 'reducedAbsDeltaPhiGgJet2p50IA_genAbsDeltaPhiGgJet2p50_nominal.root'
  OA_125: 'reducedAbsDeltaPhiGgJet2p50OA__nominal.root'
  IA_120: 'reducedAbsDeltaPhiGgJet2p50IA_genAbsDeltaPhiGgJet2p50_nominal.root'
  OA_120: 'reducedAbsDeltaPhiGgJet2p50OA__nominal.root'
  IA_130: 'reducedAbsDeltaPhiGgJet2p50IA_genAbsDeltaPhiGgJet2p50_nominal.root'
  OA_130: 'reducedAbsDeltaPhiGgJet2p50OA__nominal.root'
  Data: 'reducedAbsDeltaPhiGgJet2p50Data__nominal.root'
  
treepath: 'tagsDumper/trees'

formulas: 
  recoAbsDeltaPhiGgJet2p50: 'abs(@deltaPhi(recoPhi, recoJet2p5Phi0))'
  genAbsDeltaPhiGgJet2p50: 'abs(@deltaPhi(genPhi, genJet2p5Phi0))'

functions:
  deltaPhi: "def deltaPhi(phi1, phi2):\n\t ret = phi1 - phi2\n\t ret[ret >= np.pi] = ret[ret >= np.pi] - 2*np.pi\n\t ret[ret < -np.pi] = ret[ret < -np.pi] + 2*np.pi\n\t return ret"
