splits: 
  genPt: [0.0,5.0,10.0,15.0,20.0,25.0,30.0,35.0,45.0,60.0,80.0,100.0,120.0,140.0,170.0,200.0,250.0,350.0,450.0,10000.0]
  recoPt: [0.0,5.0,10.0,15.0,20.0,25.0,30.0,35.0,45.0,60.0,80.0,100.0,120.0,140.0,170.0,200.0,250.0,350.0,450.0,10000.0]
  sigmaMoM_decorr: [0.0, 0.0106, 0.0146, 0.0396]
  # absdZ: [0.0,1.0,100.]
 
variables: 
  CMS_hgg_mass: [100, 180]
  weight: [-inf, inf]
  centralObjectWeight: [-1000, 1000]
  NNLOPSweight: [-inf, inf]
  dZ: [-inf, inf]
  processIndex: [0,100]

cut: 'leadmva>0.397 and subleadmva>0.397'

weight: 'weight*NNLOPSweight'

systVars: []

procs:
  IA_125: 'InsideAcceptance_125_13TeV'
  OA_125: 'OutsideAcceptance_125_13TeV'
  IA_120: 'InsideAcceptance_120_13TeV'
  OA_120: 'OutsideAcceptance_120_13TeV'
  IA_130: 'InsideAcceptance_130_13TeV'
  OA_130: 'OutsideAcceptance_130_13TeV'
  Data: 'Data_13TeV'
  
categories: ['SigmaMpTTag_0']

filenames:
  IA_125: 'reducedPtIA_genPt_nominal.root'
  OA_125: 'reducedPtOA__nominal.root'
  IA_120: 'reducedPtIA_genPt_nominal.root'
  OA_120: 'reducedPtOA__nominal.root'
  IA_130: 'reducedPtIA_genPt_nominal.root'
  OA_130: 'reducedPtOA__nominal.root'
  Data: 'reducedPtData__nominal.root'
  
treepath: 'tagsDumper/trees'

# formulas: 
#  absdZ: 'abs(dZ)'
